services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=contraseña
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgressql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=contraseña
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
